  var dublin = L.marker([53.3400, -6.1439], [74, 1001, 9.6666])

  .addTo(map)
    dublin.bindPopup('<b>Dublin</b><br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/dublin-cherbourg/" class="speciallink">Dublin-Cherbourg (Irish Ferries)</a><br><a href="http://www.stenaline.ie/routes/dublin-holyhead" class="speciallink">Dublin-Holyhead (Stena Line)<br></a><a href="http://www.poferries.com/eu/liverpool-dublin" class="speciallink">Dublin-Liverpool (P&O)<br></a><a href="http://www.poferries.com/eu/liverpool-dublin" class="speciallink">Dublin-Holyhead (Irish Ferries)')
  var rosslare = L.marker([52.3400, -6.4439], [74, 1001, 9.6666])
    .addTo(map)
    rosslare.bindPopup('<b>Rosslare<br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/rosslare-pembroke/">Rosslare-Pembroke (Irish Ferries)</a><br><a href="http://www.stenaline.ie/routes/rosslare-fishguard" class="speciallink">Rosslare-Fishguard (Stena Line)<br></a><a href="http://www.irishferries.com/uk-en/routes/rosslare-cherbourg/" class="speciallink">Rosslare-Cherbourg (Irish Ferries)<br></a><a href="http://www.irishferries.com/uk-en/routes/rosslare-roscoff/" class="speciallink">Rosslare-Roscoff (Irish Ferries)</b>')
  var belfast = L.marker([54.6400, -5.899], [74, 1001, 9.6666])
    .addTo(map)
    belfast.bindPopup('<b>Belfast<br><br> <b>Operator Routes:</b> <br> <a href="http://www.stenaline.ie/routes/belfast-cairnryan">Belfast-Cairnryan (Stena Line)</a><br><a href="http://www.stenaline.ie/routes/belfast-liverpool" class="speciallink">Belfast-Liverpool (Stena Line)<br></a></b>')
    .addTo(map)
  var cork = L.marker([51.7400, -8.2439], [74, 1001, 9.6666])
    .addTo(map)
    cork.bindPopup('<b>Cork<br><br> <b>Operator Routes:</b> <br> <a href="http://www.brittanyferries.ie/ferry-routes/ireland-france-ferries/cork-roscoff">Cork-Roscoff (Brittany Ferries)</a></b>')
    .addTo(map)
  var liverpool = L.marker([53.3400, -3.1439], [74, 1001, 9.6666])
    .addTo(map)
    .bindPopup('<b>Liverpool<br><br> <b>Operator Routes:</b> <br> <a href="http://www.stenaline.ie/routes/belfast-liverpool">Liverpool-Belfast (Stena Line)</a><br><a href="http://www.poferries.com/eu/liverpool-dublin" class="speciallink">Liverpool-Dublin (P&O)<br></a></b>')
    .addTo(map)
  var holyhead = L.marker([53.2900, -4.6739], [74, 1001, 9.6666])
    .addTo(map)
    holyhead.bindPopup('<b>Holyhead<br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/dublin-holyhead/">Holyhead-Dublin (Irish Ferries)</a><br><a href="http://www.stenaline.ie/routes/dublin-holyhead" class="speciallink">Holyhead-Dublin (Stena Line)</b>')
    .addTo(map)
  var cherbourg = L.marker([49.6550, -1.6239], [74, 1001, 9.6666])
    .addTo(map)
    .bindPopup('<b>Cherbourg<br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/dublin-cherbourg/">Cherbourg-Dublin (Irish Ferries)</a><br><a href="http://www.stenaline.ie/routes/rosslare-cherbourg" class="speciallink">Cherbourg-Rosslare (Stena Line)</b>')
    .addTo(map)
  var roscoff = L.marker([48.7250, -3.9900], [74, 1001, 9.6666])
    .addTo(map)
    roscoff.bindPopup('<b>Roscoff<br><br> <b>Operator Routes:</b> <br> <a href="http://www.brittanyferries.ie/ferry-routes/ireland-france-ferries/cork-roscoff">Roscoff-Cork (Brittany Ferries)</a><br><a href="http://www.irishferries.com/uk-en/routes/rosslare-roscoff/" class="speciallink">Roscoff-Rosslare (Irish Ferries)</b>')
    .addTo(map)
  var larne = L.marker([54.850, -5.799], [74, 1001, 9.6666])
    .addTo(map)
    larne.bindPopup('<b>Larne<br><br> <b>Operator Routes:</b> <br> <a href="http://www.poferries.com/eu/larne-cairnryan">Larne-Cairnryan (P&O)</a></b>')
    .addTo(map)
  var fishguard = L.marker([51.999, -4.999], [74, 1001, 9.6666])
    .addTo(map)
    .bindPopup('<b>Fishguard<br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/rosslare-pembroke/">Fishguard-Rosslare (Stena Line)</a></b>')
    .addTo(map)
  var pembroke = L.marker([51.699, -4.929], [74, 1001, 9.6666])
      .bindPopup('<b>Pembroke<br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/rosslare-pembroke/">Pembroke-Rosslare (Irish Ferries)</a></b>')
    .addTo(map)
  var cairnryan = L.marker([54.969, -5.019], [74, 1001, 9.6666])
    .addTo(map)  
    cairnryan.bindPopup('<b>Cairnryan<br><br> <b>Operator Routes:</b> <br> <a href="http://www.stenaline.ie/routes/belfast-cairnryan">Cairnryan-Belfast (Stena Line)</a><br><a href="http://www.poferries.com/eu/larne-cairnryan" class="speciallink">Cairnryan-Larne (Stena Line)<br></a></b>')
   var dublin = L.marker([53.3400, -6.1439], [74, 1001, 9.6666])

  .addTo(map)
    dublin.bindPopup('<b>Dublin<br><br> <b>Operator Routes:</b> <br> <a href="http://www.irishferries.com/uk-en/routes/dublin-cherbourg/" class="speciallink">Dublin-Cherbourg (Irish Ferries)</a><br><a href="http://www.stenaline.ie/routes/dublin-holyhead" class="speciallink">Dublin-Holyhead (Stena Line)<br></a><a href="http://www.poferries.com/eu/liverpool-dublin" class="speciallink">Dublin-Liverpool (P&O)<br></a><a href="http://www.poferries.com/eu/liverpool-dublin" class="speciallink">Dublin-Holyhead (Irish Ferries)</b>')
    .openPopup();